apt:
  packages:
    - apt-transport-https=1.6.12ubuntu0.2
    - bison=2:3.0.4.dfsg-1build1
    - build-essential=12.4ubuntu1
    - build-essential=12.4ubuntu1
    - containerd.io=1.4.3-1
    - default-jre=2:1.11-68ubuntu1~18.04.1
    - docker-ce-cli=5:20.10.2~3-0~ubuntu-bionic
    - docker-ce=5:20.10.2~3-0~ubuntu-bionic
    - figlet=2.2.5-3
    - fonts-firacode=1.204-2
    - gcc=4:7.4.0-1ubuntu2.3
    - gh=1.5.0
    - gnupg2=2.2.4-1ubuntu1.3
    - google-cloud-sdk-skaffold=323.0.0-0
    - google-cloud-sdk=323.0.0-0
    - httpie=0.9.8-2
    - iotop=0.6-2
    - jq=1.5+dfsg-2
    - kubectl=1.20.2-00
    - libbz2-dev=1.0.6-8.1ubuntu0.2
    - libffi-dev=3.2.1-8
    - liblzma-dev=5.2.2-1.3
    - libncurses5-dev=6.1-1ubuntu1.18.04
    - libnss3-tools=2:3.35-2ubuntu2.12
    - libreadline-dev=7.0-3
    - libsqlite3-dev=3.22.0-1ubuntu0.4
    - libssl-dev=1.1.1-1ubuntu2.1~18.04.7
    - libxml2-dev=2.9.4+dfsg1-6.1ubuntu1.3
    - llvm=1:6.0-41~exp5~ubuntu1
    - lolcat=42.0.99-1
    - make=4.1-9.1ubuntu1
    - mtr=0.92-1
    - neofetch=3.4.0-1
    - nmap=7.60-1ubuntu5
    - nmon=16g+debian-3
    - osquery=4.5.1-1.linux
    - pack-cli=0.16.0-0ubuntu1~bionic
    - pinentry-curses=1.1.0-1
    - pinentry-gtk2=1.1.0-1
    - pkg-config=0.29.1-0ubuntu2
    - postgresql-client=10+190ubuntu0.1
    - python3-pip=9.0.1-2.3~ubuntu1.18.04.4
    - rlwrap=0.43-1
    - rng-tools=5-0ubuntu4
    - ruby2.6-dev=2.6.6-1bbox1~bionic1
    - ruby2.6=2.6.6-1bbox1~bionic1
    - screen=4.6.2-1ubuntu1
    - shellcheck=0.4.6-1
    - tk-dev=8.6.0+9
    - tree=1.7.0-5
    - unzip=6.0-21ubuntu1.1
    - xz-utils=5.2.2-1.3
    - zip=3.0-11build1
    - zlib1g-dev=1:1.2.11.dfsg-0ubuntu2
npm:
  packages:
    - name: express
      version: 4.17.1
    - name: serverless
      version: 2.18.0
    - name: snyk
      version: 1.437.3
    - name: stts
      version: 1.2.2
pip:
  packages:
    - docker==4.4.1
    - detect-secrets==0.14.3
    - pre-commit==2.9.3
