alias clear="clear && figlet $(cat .title) | lolcat --seed 18" # overrides clear
alias home="cd ~/ && clear" # overrides clear
alias profile="bat ~/.bash_profile" # overrides clear
# <!-- alias END -->

export PATH=$PATH:/go/bin # golang
export PATH=$PATH:$HOME/.local/bin # pip3
# <!-- path END -->

GOOGLE_APPLICATION_CREDENTIALS=$HOME/.gcloud.json
export GOOGLE_APPLICATION_CREDENTIALS

if [ -f $GOOGLE_APPLICATION_CREDENTIALS ]; then
    GOOGLE_SERVICE_ACCOUNT="$(cat $HOME/.gcloud.json | jq -r '.client_email')"
    export GOOGLE_SERVICE_ACCOUNT
    GOOGLE_PROJECT="$(cat $HOME/.gcloud.json | jq -r '.project_id')"
    export GOOGLE_PROJECT
fi
# <!-- google END -->

export BAT_CONFIG_PATH="$HOME/.config/bat.conf"
GPG_TTY="$(tty)"
export GPG_TTY
# <!-- env END -->

eval "$(starship init bash)"
# <!-- eval END -->

clear
# <!-- clear END -->

bash "$HOME/.scripts/init.sh"
# <!-- init END -->
