apt:
  repos:
    - name: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    - name: gcloud
      repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    - name: gh
      repo: deb https://cli.github.com/packages bionic main
    - name: osquery
      repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
    - name: packs
      repo: ppa:cncf-buildpacks/pack-cli
    - name: ruby
      repo: ppa:brightbox/ruby-ng
  packages:
    - apt-transport-https=1.6.12ubuntu0.2
    - bison=2:3.0.4.dfsg-1build1
    - build-essential=12.4ubuntu1
    - build-essential=12.4ubuntu1
    - containerd.io=1.4.3-1
    - default-jre=2:1.11-68ubuntu1~18.04.1
    - docker-ce-cli=5:20.10.2~3-0~ubuntu-bionic
    - docker-ce=5:20.10.2~3-0~ubuntu-bionic
    - figlet=2.2.5-3
    - fonts-firacode=1.204-2
    - gcc=4:7.4.0-1ubuntu2.3
    - gh=1.5.0
    - gnupg2=2.2.4-1ubuntu1.3
    - google-cloud-sdk-skaffold=323.0.0-0
    - google-cloud-sdk=323.0.0-0
    - httpie=0.9.8-2
    - iotop=0.6-2
    - jq=1.5+dfsg-2
    - kubectl=1.20.2-00
    - libbz2-dev=1.0.6-8.1ubuntu0.2
    - libffi-dev=3.2.1-8
    - liblzma-dev=5.2.2-1.3
    - libncurses5-dev=6.1-1ubuntu1.18.04
    - libnss3-tools=2:3.35-2ubuntu2.12
    - libreadline-dev=7.0-3
    - libsqlite3-dev=3.22.0-1ubuntu0.4
    - libssl-dev=1.1.1-1ubuntu2.1~18.04.7
    - libxml2-dev=2.9.4+dfsg1-6.1ubuntu1.3
    - llvm=1:6.0-41~exp5~ubuntu1
    - lolcat=42.0.99-1
    - make=4.1-9.1ubuntu1
    - mtr=0.92-1
    - neofetch=3.4.0-1
    - nmap=7.60-1ubuntu5
    - nmon=16g+debian-3
    - osquery=4.5.1-1.linux
    - pack-cli=0.17.0-0ubuntu1~bionic
    - pinentry-curses=1.1.0-1
    - pinentry-gtk2=1.1.0-1
    - pkg-config=0.29.1-0ubuntu2
    - postgresql-client=10+190ubuntu0.1
    - python3-pip=9.0.1-2.3~ubuntu1.18.04.4
    - rlwrap=0.43-1
    - rng-tools=5-0ubuntu4
    - ruby2.6-dev=2.6.6-1bbox1~bionic1
    - ruby2.6=2.6.6-1bbox1~bionic1
    - screen=4.6.2-1ubuntu1
    - shellcheck=0.4.6-1
    - sqlite3=3.22.0-1ubuntu0.4
    - tk-dev=8.6.0+9
    - tree=1.7.0-5
    - unzip=6.0-21ubuntu1.1
    - xz-utils=5.2.2-1.3
    - zip=3.0-11build1
    - zlib1g-dev=1:1.2.11.dfsg-0ubuntu2
deb:
  packages:
    - name: bat
      url: https://github.com/sharkdp/bat/releases/download/v0.17.1/bat_{{ versions.bat }}_amd64.deb
    - name: octant
      url: https://github.com/vmware-tanzu/octant/releases/download/v{{ versions.octant }}/octant_{{ versions.octant }}_Linux-64bit.deb
    - name: scala
      url: https://downloads.lightbend.com/scala/{{ versions.scala }}/scala-{{ versions.scala }}.deb
    - name: trivy
      url: https://github.com/aquasecurity/trivy/releases/download/v{{ versions.trivy }}/trivy_{{ versions.trivy }}_Linux-64bit.deb
    - name: xcaddy
      url: https://github.com/caddyserver/xcaddy/releases/download/v{{ versions.xcaddy }}/xcaddy_{{ versions.xcaddy }}_linux_amd64.deb
archive:
  packages:
    - name: docker-credential-gcr
      src: https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v{{ versions.docker_credential_gcr }}/docker-credential-gcr_linux_amd64-{{ versions.docker_credential_gcr }}.tar.gz
      dest: /usr/local/bin/
    - name: doctl
      src: https://github.com/digitalocean/doctl/releases/download/v{{ versions.doctl }}/doctl-{{ versions.doctl }}-linux-amd64.tar.gz
      dest: /usr/local/bin/
    - name: golang
      src: https://golang.org/dl/go{{ versions.golang }}.linux-amd64.tar.gz
      dest: /
    - name: packer
      src: https://releases.hashicorp.com/packer/{{ versions.packer }}/packer_{{ versions.packer }}_linux_amd64.zip
      dest: /usr/local/bin/
url:
  packages:
#    - name: cloudquery
#      url: https://github.com/cloudquery/cloudquery/releases/download/v{{ versions.cloudquery }}/cloudquery_Linux_x86_64
#      dest: /usr/local/bin/cloudquery
    - name: cst
      url: https://storage.googleapis.com/container-structure-test/v{{ versions.cst }}/container-structure-test-linux-amd64
      dest: /usr/local/bin/container-structure-test
    - name: hey
      url: https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
      dest: /usr/local/bin/hey
shell:
  packages:
    - name: bat
      cmd: curl -fsSL https://starship.rs/install.sh | bash -s -- -y
      creates: /usr/local/bin/starship
    - name: clojure
      cmd: curl -fLSs https://download.clojure.org/install/linux-install-{{ versions.clojure }}.sh | sudo bash
      creates: /usr/local/bin/clj
    - name: circleci
      cmd: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | VERSION={{ versions.circleci }} sudo bash
      creates: /usr/local/bin/circleci
    - name: golangci
      cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin "v{{ versions.golangci_lint }}"
      creates: /usr/local/bin/golangci-lint
    - name: gvm
      cmd: curl -fLSs https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
      creates: /home/vagrant/.gvm/bin/gvm
    - name: inspec
      cmd: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -v {{ versions.inspec }} -P inspec
      creates: /usr/bin/inspec
    - name: rust
      cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y
      creates: ~/.cargo/bin/rustc
npm:
  packages:
    - name: express # https://www.npmjs.com/package/express
      version: 4.17.1
    - name: serverless # https://www.npmjs.com/package/serverless
      version: 2.21.1
    - name: snyk # https://www.npmjs.com/package/snyk
      version: 1.440.1
    - name: stts # https://www.npmjs.com/package/stts
      version: 1.2.2
pip:
  packages:
    - detect-secrets==0.14.3 # https://pypi.org/project/detect-secrets/
    - pre-commit==2.10.0 # https://pypi.org/project/pre-commit/
